### ISSUE TITLE
Blank screen at makecode.microbit.org

### ISSUE THREAD

**Issue by jtcircus** [microsoft/pxt-microbit#5038]
**Describe the bug**
When doing initial load of makecode.microbit.org, getting a blank screen. Some students can get in, some students get a blank screen. 

**To Reproduce**
type in makecode.microbit.org

**Expected behavior**
Load home page

**Screenshots**
![image](https://user-images.githubusercontent.com/50813509/229200662-648ec999-f890-4b42-ba0d-afd025d2ad8d.png)

**micro:bit version (please complete the following information):**

Not related to micro:bit hardware.

**Desktop (please complete the following information):**
 - Chromebook:  does not need update:  Your Chromebook is up to date
Version 108.0.5359.172 (Official Build) (64-bit)

**Additional context**
Our school district tech department says that all student chromebooks are configured the same. We can't figure out why some students are unable to access the website.

**Comment by abchatra** [comment]
@jtcircus sorry. Can you load the following site and see if all the domains can be reached? 
https://makecode.microbit.org/domains

**Comment by jtcircus** [comment]
Failure on azureedge and immersive reader
What do I do now?Thank you for your help.
Jackie

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 31, 2023 at 11:38 AM, Abhijith ***@***.***> wrote:   


@jtcircus sorry. Can you load the following site and see if all the domains can be reached?
https://makecode.microbit.org/domains

**Comment by abchatra** [comment]
You need to ask your IT admin to add these to the unblocked list. Especially following domain needs to be unblocked by your IT admin:
https://pxt.azureedge.net

It is a CDN on html\javacript. 

I would suggest talk to IT admin and ask to unblock all the domains listed there.

**Comment by abchatra** [comment]
This is a network blocking issue. I am assuming this is resolved.

**Comment by jtcircus** [comment]
I resolved this issue with sites at this link that I received from Katie Henry.Frequently Asked Questions  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Frequently Asked Questions
 
Frequently asked questions and answers from our users.
  |   |

  |

  |

  
I still get failures at 2 sites from your list, but my students are able to now access the makecode editor.
Thank you for your help.Jackie


Sent from Yahoo Mail on Android 
 
  On Sun, Apr 16, 2023 at 1:32 PM, Abhijith ***@***.***> wrote:   


This is a network blocking issue. I am assuming this is resolved.
